export const Svgs = [
    { path: 'assets/svgs/altbalaji_logo.svg', name: 'alt_logo' },
    { path: 'assets/svgs/Vector-back.svg', name: 'back-arrow' },
    { path: 'assets/svgs/close.svg', name: 'close-media' },
    { path: 'assets/svgs/plus.svg', name: 'plus' },
    { path: 'assets/svgs/share.svg', name: 'share' },
    { path: 'assets/svgs/mic.svg', name: 'mic' },
    { path: 'assets/svgs/crown.svg', name: 'crown' },
    { path: 'assets/svgs/crown.svg', name: 'crown2' },
    { path: 'assets/svgs/crown_main.svg', name: 'crown_main' },
    { path: 'assets/svgs/info.svg', name: 'info' },
    { path: 'assets/svgs/search.svg', name: 'search' },
    { path: 'assets/svgs/user.svg', name: 'user' },
    { path: 'assets/svgs/amazonpay.svg', name: 'amazonpay' },
    { path: 'assets/svgs/PAYU.svg', name: 'payu' },
    { path: 'assets/svgs/paytm.svg', name: 'paytm' },
    { path: 'assets/svgs/MobiKwik.svg', name: 'mobikwik' },
    { path: 'assets/svgs/Mobile_Wallets.svg', name: 'Mobile_Wallets' },
    { path: 'assets/svgs/Net_Banking.svg', name: 'net_banking' },
    { path: 'assets/svgs/right-arrow.svg', name: 'viewArrow' },
    { path: 'assets/svgs/settings.svg', name: 'setting' },
    { path: 'assets/svgs/tick.svg', name: 'tick' },
    { path: 'assets/svgs/questionedMark.svg', name: 'stop' }
]
