export class ApiConstants {
    static SIGNUP = 'user/add';
    static LOGIN = 'user/login';
    static OTP_LOGIN = 'user/login/phone';
    static VERIFY_OTP = 'user/verify_otp';
    static USER_EXIST_CHECK = 'user/lookup';
    static ACCESS_TOKEN = 'auth/access/token';
    static IS_ALLOWED='device/ifallowed'
    static HOME_CONTENT = 'content/home3';
    static LOGOUT= 'auth/device/logout'
    static SUBSCRIBE = 'spackage/subscription/device/web';
    static EDIT_USER = 'user/edit';
    static CONTACT_US = 'contactus/send';
    static PARENTAL_CREATE_PIN = 'parental/create/pin';
    static RESTRICTION = 'parental/restriction/level';
    static VALIDATE_PIN = 'parental/auth';
    static CHANGE_PIN = 'parental/pin/change';
    static FORGET_PASS_GENERATE_OTP = 'parental/forget/otp/send';
    static VALIDATE_FORGET_PASS_OTP = 'user/verify_otp';
    static FORGET_PIN_RESET = 'parental/forget/pin';
    static CATEGORYL_LIST = 'content/list/device/web';
    static WATCH_LIST = 'content/watchlist/device/web';
    static CLEAR_WATCH_LIST = 'clear/watchlist';
    static RECOMMENDED_LIST = 'content/recomended/device/web';
    static ANALYTICS = 'analyticapi/analytics-data';
    static MOST_VIEWED = 'content/most_req';
    static CONTINUE='content/watchlist/device/web';
    static CONTENT_LIKE_DISLIKE = 'content/like';
    static CONTENT_LIKE_DISLIKE_BEHAVIOUR = 'content/user_behavior';
    static ADD_REMOVE_TO_WATCHLIST = 'content/addwatchlist';
    static SEARCH_KEY = 'content/list/device/web';
    static TRANSACTION_HISTORY = 'transaction/history';
    static DEVICE_LIST = 'device/list';
    static SEASON_LIST = 'content/list/device/web';
    static BILLING_HISTORY = 'billing/history';
    static CONSENT_LETTER = 'subscribe/newsletter';
    static Redeem = 'subscription/redeem_coupon/device/web';
    static FORGOT_PASSWORD='user/forgot/otp';
    static RESET_PASSWORD='user/resetpassword';
    static ADVANCED_SEARCH='content/advance/search/device/web/current_offset/0/max_counter/10';
    static ADDPOPULAR_search='add/popular/content';
    static ACTIVATION_CODE ='activation/validate';
    static AUTO_SUGGEST='content/autosuggest';
}