name: Deploy Vive Web Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: npx ng build --configuration production

      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/deploy"
          strip_components: 1

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf /var/www/vive_web/*
            sudo cp -r /home/ubuntu/deploy/* /var/www/vive_web/
            sudo systemctl restart nginx
